project_id = "algqekyoaskhdxuegirh"

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.create-payment-signup]
verify_jwt = false

[functions.verify-payment-and-signup]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false