// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://algqekyoaskhdxuegirh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsZ3Fla3lvYXNraGR4dWVnaXJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MjU2MjcsImV4cCI6MjA2OTEwMTYyN30.ojh4IF4CTY0gxT--a9KgKv_Ns5_XvfL0lOS7j8oUGxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});